name: "Publish release on tag push"

on:
  push:
    tags:
      - "v*"

jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for CHANGELOG.md
        uses: actions/checkout@v2

      - name: Get package info
        id: package
        uses: codex-team/action-nodejs-package-info@v1

      - name: Publish Release to Github
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: ${{ env.P_COLLECTION_FILE_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
